version: '3.4'

services:
  inpgenweb:
    image: inpgenweb
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5002:5002
    volumes:
      - ./app:/api
      - uploads:/app/uploads
    environment:
      - FLASK_APP=app/api.py
    depends_on:
      - redis
  worker:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./celery-queue:/queue', 'uploads:/queue/uploads']
  monitor:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    command:  ['celery', '-A', 'tasks', 'flower', ]
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - worker
    volumes: ['./celery-queue:/queue', 'uploads:/queue/uploads']
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  uploads:

